### PR TITLE
Update CoL list of columns

### PR DESCRIPTION
**Pull request by maxpatiiuk**
CoL added new columns to their .tsv files (and to make matters worse, the added them at the beginning of the file, rather than at the end), thus all columns were off by 2 when the script tried to import the data

- Add new columns CoL added to their exports
- Add a simple mechanism for detecting when columns change again (rather than something complex that automatically figures out which columns to use)

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
I copied the files into the back-end container, see error when trying to refresh data:

```sh
~/taxa_tree_col $ cd /home/specify/taxa_tree_col/back_end/ && /home/specify/venv/bin/python3 refresh_data.py
Traceback (most recent call last):
  File "/home/specify/taxa_tree_col/back_end/refresh_data.py", line 9, in <module>
    from back_end.expected_columns import expected_columns
ModuleNotFoundError: No module named 'back_end'
~/taxa_tree_col/back_end $
```

**Comment by grantfitzsimmons** [comment]
Is this an issue on my end or did you test these changes?

**Comment by maxpatiiuk** [comment]
If you have a chance, could you try replacing that line with:
```python
from .expected_columns import expected_columns
```

or 

```python
from expected_columns import expected_columns
```

and see if that fixes it?

**Comment by maxpatiiuk** [comment]
@grantfitzsimmons could you approve this pull request if it worked alright after the change you did?

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
